Use zap as a logger and add http request logs
giantswarm/loki-multi-tenant-proxy pull request #69
Opened 2023-11-30 15:13 UTC by QuentinBisson

Towards https://github.com/giantswarm/giantswarm/issues/25656

This PR:

- introduces zap as the main logger (adds structured logging)
- ensures we are logging http requests fields to be able to debug authentication errors and the likes

### Checklist

- [x] Update changelog in CHANGELOG.md.

2023-11-30 15:13 UTC, QuentinBisson commented on internal/app/loki-multi-tenant-proxy/auth.go
> +			if !authConfig.KeepOrgID {
nitpicking

2023-11-30 16:54 UTC, hervenicol commented on go.mod
> +go 1.21
:astonished: :chart_with_upwards_trend: :fire: :rocket: :+1:

2023-12-04 10:16 UTC, hervenicol commented on internal/app/loki-multi-tenant-proxy/logging.go
> +				logger.Info("Success", fields...)
I mean, how do I tell it I only want WARN+ logs to show?

2023-12-04 11:35 UTC, QuentinBisson commented
Current logs with zap:

```
{"level":"info","ts":1701689693.7839596,"caller":"loki-multi-tenant-proxy/logging.go:50","msg":"Success","method":"POST","url":"http://loki-write.loki.svc.cluster.local:3100/loki/api/v1/push","proto":"HTTP/1.1","status":204,"ip":"100.64.2.90:45948","user_agent":"GrafanaAgent/v0.37.2","took":0.001760647}
{"level":"info","ts":1701689693.7848904,"caller":"loki-multi-tenant-proxy/logging.go:50","msg":"Success","method":"POST","url":"http://loki-write.loki.svc.cluster.local:3100/loki/api/v1/push","proto":"HTTP/1.1","status":204,"ip":"100.64.8.235:45454","user_agent":"GrafanaAgent/v0.37.2","took":0.001613615}
{"level":"info","ts":1701689693.8157227,"caller":"loki-multi-tenant-proxy/logging.go:50","msg":"Success","method":"POST","url":"http://loki-write.loki.svc.cluster.local:3100/loki/api/v1/push","proto":"HTTP/1.1","status":204,"ip":"100.64.2.90:45950","user_agent":"promtail/2.8.4","took":0.001944818}
{"level":"info","ts":1701689693.844576,"caller":"loki-multi-tenant-proxy/logging.go:50","msg":"Success","method":"POST","url":"http://loki-write.loki.svc.cluster.local:3100/loki/api/v1/push","proto":"HTTP/1.1","status":204,"ip":"100.64.2.90:45962","user_agent":"promtail/2.8.4","took":0.002783095}
{"level":"info","ts":1701689693.9577487,"caller":"loki-multi-tenant-proxy/logging.go:50","msg":"Success","method":"POST","url":"http://loki-write.loki.svc.cluster.local:3100/loki/api/v1/push","proto":"HTTP/1.1","status":204,"ip":"100.64.8.235:58720","user_agent":"promtail/2.8.4","took":0.00219915}
{"level":"info","ts":1701689694.1322494,"caller":"loki-multi-tenant-proxy/logging.go:50","msg":"Success","method":"POST","url":"http://loki-write.loki.svc.cluster.local:3100/loki/api/v1/push","proto":"HTTP/1.1","status":204,"ip":"100.64.2.90:45968","user_agent":"promtail/2.8.4","took":0.003513488}
{"level":"info","ts":1701689694.2529771,"caller":"loki-multi-tenant-proxy/logging.go:50","msg":"Success","method":"POST","url":"http://loki-write.loki.svc.cluster.local:3100/loki/api/v1/push","proto":"HTTP/1.1","status":204,"ip":"100.64.8.235:58736","user_agent":"promtail/2.8.4","took":0.00317448}
{"level":"info","ts":1701689694.2686863,"caller":"loki-multi-tenant-proxy/logging.go:50","msg":"Success","method":"POST","url":"http://loki-write.loki.svc.cluster.local:3100/loki/api/v1/push","proto":"HTTP/1.1","status":204,"ip":"100.64.8.235:58752","user_agent":"promtail/2.8.4","took":0.00203952}
```

Log level can be set using the new log-level flag :)

2023-12-04 16:11 UTC, TheoBrigitte commented on internal/app/loki-multi-tenant-proxy/server.go
> +	logger := zap.Must(zapConfig.Build())
Is there a way to handle error here ?

2023-12-04 16:15 UTC, QuentinBisson commented on internal/app/loki-multi-tenant-proxy/server.go
> +	logger := zap.Must(zapConfig.Build())
Well, i'd rather we panic if flag is incorrect. How would you handle it ?

2023-12-04 17:18 UTC, hervenicol commented on internal/app/loki-multi-tenant-proxy/logging.go
> +				logger.Info("Success", fields...)
Now there's the flag I'm quite happy :)
We just have to make sure we update our charts, because we don't want INFO logs on our installs.

2023-12-04 20:21 UTC, TheoBrigitte requested changes
I would rather avoid to use `Fatal` as this would interrupt execution and instead log the error (if needed) and return it.

2023-12-04 20:21 UTC, TheoBrigitte commented on internal/app/loki-multi-tenant-proxy/server.go
> +	logger := zap.Must(zapConfig.Build())
I would rather have something like
```suggestion
	logger, err := zapConfig.Build()
	if err != nil {
	    log.Print("Could not construct logger", zap.Error(err))
	    return err
	}
```

2023-12-04 20:21 UTC, TheoBrigitte commented on internal/app/loki-multi-tenant-proxy/server.go
> +		panic(fmt.Sprintf("Could not parse log level %v", zap.Error(err)))
```suggestion
		log.Printf("Could not parse log level %v", zap.Error(err))
		return err
```

2023-12-04 20:21 UTC, TheoBrigitte commented on internal/app/loki-multi-tenant-proxy/server.go
> +		logger.Fatal("Can not create error logger", zap.Error(err))
I know `Fatal` would interrupt execution, but being explicit helps with consistency.

```suggestion
		logger.Print("Can not create error logger", zap.Error(err))
		return err
```

2023-12-04 20:21 UTC, TheoBrigitte commented on internal/app/loki-multi-tenant-proxy/server.go
> +		logger.Fatal("Loki multi tenant proxy can not start", zap.Error(err))
```suggestion
		logger.Print("Loki multi tenant proxy can not start", zap.Error(err))
```

2023-12-05 09:15 UTC, QuentinBisson commented on internal/app/loki-multi-tenant-proxy/server.go
> +		logger.Fatal("Can not create error logger", zap.Error(err))
Well I do not agree. We should know that logger.Fatal exists and using print makes it an info log, not a fatal one

2023-12-11 09:40 UTC, TheoBrigitte commented on internal/app/loki-multi-tenant-proxy/logging.go
> +				logger.Info("Success", fields...)
We decided to keep INFO as default within the app and set WARN when deploying it, as INFO would be too verbose for us currently.

2023-12-11 09:50 UTC, QuentinBisson commented on internal/app/loki-multi-tenant-proxy/server.go
> +			log.Printf("Could not parse log level %v", err)
Fixed :)

2023-12-11 09:51 UTC, QuentinBisson commented on internal/app/loki-multi-tenant-proxy/server.go
> +		logger.Fatal("Loki multi tenant proxy can not start", zap.Error(err))
Fixed

2023-12-11 09:51 UTC, QuentinBisson commented on internal/app/loki-multi-tenant-proxy/server.go
> +		logger.Fatal("Can not create error logger", zap.Error(err))
Fixed

2023-12-11 10:03 UTC, QuentinBisson commented
Tested custom error and we need an extra log as the error is not logged by the lib otherwise:

k logs -n loki loki-multi-tenant-proxy-59f4ff9787-w8bhx -c loki-multi-tenant-proxy-write
2023/12/11 10:02:23 Error is here (my own print log)

2023-12-11 10:13 UTC, QuentinBisson commented
@TheoBrigitte I moved to use the framework custom error (using cli.Exit). That wraps the error into a custom type that then gets logged into stdout. Otherwise, we have to use a custom error handler.

2023-12-11 10:14 UTC, QuentinBisson commented on internal/app/loki-multi-tenant-proxy/server.go
> +		return cli.Exit(fmt.Sprintf("Could not create standard logger %v", err), -1)
https://cli.urfave.org/v2/examples/exit-codes/ This explains the use of cli.Exit

2023-12-11 14:53 UTC, TheoBrigitte approved these changes
LGTM

2023-12-11 14:59 UTC, merged